# syntax=docker/dockerfile:1.7

ARG BASE_IMAGE=ghcr.io/usagi-org/ai-goofish-base:latest

FROM ${BASE_IMAGE}

WORKDIR /app

COPY dist /app/dist

COPY src /app/src
COPY spider_v2.py /app/spider_v2.py
COPY prompts /app/prompts
COPY static /app/static
COPY config.json.example /app/config.json.example

EXPOSE 8000

CMD ["python", "-m", "src.app"]
